FROM golang:{{ .GoVersion }} AS builder

WORKDIR /app
ENV GO111MODULE=on
ENV GOPROXY=https://proxy.golang.org,direct

COPY . .
RUN make build

FROM alpine:3.20
WORKDIR /app

RUN apk add --no-cache ca-certificates tzdata

COPY --from=builder /app/bin/{{ .BinaryName }} /app/{{ .BinaryName }}
COPY --from=builder /app/config/config_docker.yml /app/config/config.yml

RUN chmod +x /app/{{ .BinaryName }}
CMD ["/app/{{ .BinaryName }}", "http", "-c", "/app/config/config.yml"]
